server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quizes_db?createDatabaseIfNotExist=true
    username: root
    password: my1234
  application:
    name: quiz_service
  jpa:
    hibernate:
      ddl-auto: update
