

server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quiz_db?createDatabaseIfNotExist=true
    username: root
    password: my1234
  application:
    name: question-service
  jpa:
    hibernate:
      ddl-auto: update



